// ESLint Configuration for GitLab Repository
// Enhanced with security and code quality plugins
import security from 'eslint-plugin-security';
import sonarjs from 'eslint-plugin-sonarjs';

export default [
    // Global Ignores to prevent EMFILE and binary/large file scans
    {
        ignores: [
            "**/node_modules/**",
            "node_modules/",
            "**/dist/**",
            "dist/",
            "**/public/**",
            "public/",
            "**/swf/**",
            "**/images/**",
            "**/audio/**",
            "**/*.min.js",
            "**/kepler_data_parsed.js",
            "**/*.json",
            "**/*.map",
            "package-lock.json",
            "package.json",
            "**/*.log",
            "**/*.txt",
            "**/*.md",
            "**/*.css",
            "**/*.html",
            "**/experimental/**",
            "**/*.bik",
            "**/*.dat",
            "**/*.pack",
            "**/*.exe",
            "**/*.dll",
            "**/*.tga",
            "**/*.sav",
            "**/*.cab",
            "**/*.wfc",
            "**/*.rwm",
            "**/*.idx",
            "**/*.hgt",
            "**/*.py",
            "**/*.yaml",
            "**/*.yml",
            "**/*.service",
            "**/*.sh",
            "**/Dockerfile",
            "**/*.sol",
            "**/*.ps1",
            // Config & Binary Ignores
            "**/.gitattributes",
            "**/.gitignore",
            "**/.prettierignore",
            "**/.prettierrc",
            "**/LICENSE",
            "**/CNAME",
            "**/*.png",
            "**/*.opju",
            "**/*.mht",
            "**/*.pdf",
            "**/*.kt",
            "**/*.kts",
            "**/*.pro",
            "**/gradlew",
            "**/gradle/**",
            "**/build.gradle.kts",
            "**/settings.gradle.kts",
            // Problematic/Experimental JS
            "adaptive-learning.js",
            "ai-powered-tutoring.js",
            "**/*.sql",
            "**/*.txt",
            "**/*.csv",
            "**/*.xml",
            "**/*.bat",
            "**/*.jsonl",
            "**/.pylintrc",
            "**/.dockerignore",
            "**/*cripts and loader*",
            "**/*.webp",
            "**/*.properties",
            "**/android-app/**",
            // Starsector game folder - too many files causes EMFILE error
            "**/Starsector/**",
            "Starsector/",
            "mods_full_backup/GraphicsLib/javadoc/**",
            "cheerpj-3.0/**",
            "cj3*.js",
            "cheerpj*/**",
            "**/*cj3*.js",
            "**/*natives*",
            "cheerpj.js",
            "cheerpj-dom.js",
            "loader3.js"
        ]
    },
    // Browser/Client-side configuration
    {
        files: ["*.js", "!backend/**/*.js", "!stellar-ai-cli/**/*.js", "!count-exoplanets.js", "!download-new-music.js", "!extract-wix-graph.js", "!package-cli.js", "!setup-music.js", "!kepler_data_parsed.js"],
        plugins: {
            security,
            sonarjs
        },
        languageOptions: {
            ecmaVersion: "latest",
            sourceType: "module",
            globals: {
                KEPLER_DATABASE: "readonly",
                authManager: "readonly",
                supabase: "readonly",
                SUPABASE_CONFIG: "readonly",
                USE_SUPABASE: "readonly",
                puter: "readonly",
                puterAuthToken: "readonly",
                LargeExoplanetLoader: "readonly",
                console: "readonly",
                document: "readonly",
                window: "readonly",
                localStorage: "readonly",
                sessionStorage: "readonly",
                fetch: "readonly",
                setTimeout: "readonly",
                setInterval: "readonly",
                clearTimeout: "readonly",
                clearInterval: "readonly",
                requestAnimationFrame: "readonly",
                cancelAnimationFrame: "readonly",
                TextEncoder: "readonly",
                TextDecoder: "readonly",
                crypto: "readonly",
                btoa: "readonly",
                atob: "readonly",
                alert: "readonly",
                confirm: "readonly",
                location: "readonly",
                showModal: "readonly",
                hideModal: "readonly",
                IntersectionObserver: "readonly",
                Audio: "readonly",
                URL: "readonly",
                Blob: "readonly",
                FileReader: "readonly",
                FormData: "readonly",
                MutationObserver: "readonly",
                Event: "readonly",
                CustomEvent: "readonly",
                Chart: "readonly",
                THREE: "readonly",
                PerformanceObserver: "readonly",
                CompressionStream: "readonly",
                DecompressionStream: "readonly",
                faceapi: "readonly",
                tf: "readonly",
                ort: "readonly",
                cocoSsd: "readonly",
                Tesseract: "readonly",
                cv: "readonly",
                // Browser APIs
                ResizeObserver: "readonly",
                event: "readonly",
                module: "readonly",
                require: "readonly",
                exports: "readonly",
                process: "readonly",
                Buffer: "readonly",
                __dirname: "readonly",
                __filename: "readonly",
                navigator: "readonly",
                performance: "readonly",
                indexedDB: "readonly",
                WebSocket: "readonly",
                AbortController: "readonly",
                AbortSignal: "readonly",
                ServiceWorkerRegistration: "readonly",
                gtag: "readonly",
                Planet3DViewer: "readonly",
                StarsectorAuth: "readonly",
                cheerpjInit: "readonly",
                cheerpjRunMain: "readonly",
                cheerpjCreateDisplay: "readonly",
                cheerpjAddStringFile: "readonly",
                html2canvas: "readonly",
                bootstrap: "readonly",
                Stripe: "readonly",
                google: "readonly",
                caches: "readonly",
                // Exoplanet Pioneer Game Classes
                SupabaseService: "readonly",
                AlienEcosystem: "readonly",
                CraftingManager: "readonly",
                DroneController: "readonly",
                OrbitalManager: "readonly",
                ShipDesigner: "readonly",
                FleetManager: "readonly",
                DiplomacyManager: "readonly",
                TradeManager: "readonly",
                AchievementManager: "readonly",
                EventManager: "readonly",
                MultiplayerManager: "readonly",
                PerformanceManager: "readonly",
                MilitarySystem: "readonly",
                GalaxyView: "readonly",
                PlanetGenerator: "readonly",
                getComputedStyle: "readonly",
                ImageData: "readonly",
                customElements: "readonly",
                CSS: "readonly",
                ScrollTimeline: "readonly",
                SharedWorker: "readonly",
                gemini: "readonly",
                global: "readonly",
                EventTarget: "readonly",
                SupabaseAuthManager: "readonly",
                StarSystemBuilder: "readonly",
                requestIdleCallback: "readonly",
                prompt: "readonly",
                // Missing Browser Globals
                Image: "readonly",
                File: "readonly",
                ethers: "readonly",
                URLSearchParams: "readonly",
                speechSynthesis: "readonly",
                SpeechSynthesisUtterance: "readonly",
                Notification: "readonly",
                Intl: "readonly",
                Response: "readonly",
                // Missing Node/CommonJS Globals (for mixed files)
                require: "readonly",
                process: "readonly",
                exports: "readonly",
                __dirname: "readonly",
                // jQuery
                $: "readonly",
                jqGrid: "readonly",
                dataGrid: "readonly",
                // Firebase & Auth
                FIREBASE_CONFIG: "readonly",
                currentUser: "readonly",
                onMessage: "readonly",
                getToken: "readonly",
                GEMINI_API_KEY: "readonly",
                NDEFReader: "readonly",
                planetDiscoveryAnalyticsTracking: "readonly",
                copyJqGridToDataGrid: "readonly",
                SimpleNoise: "readonly",
                Element: "readonly",
                GAME_ASSET_MANIFEST: "readonly",
                OffscreenCanvas: "readonly",
                ImageBitmap: "readonly",
                Request: "readonly",
                chrome: "readonly",
                MessageChannel: "readonly",
                AudioContext: "readonly",
                OfflineAudioContext: "readonly",
                importScripts: "readonly",
                Sentry: "readonly",
                AnimationSequence: "readonly",
                AudioWorklet: "readonly",
                AudioWorkletNode: "readonly",
                EventSource: "readonly",
                XRWebGLLayer: "readonly",
                Vector2: "readonly",
                Vector3: "readonly",
                Matrix3: "readonly",
                Matrix4: "readonly",
                Quaternion: "readonly",
                Color: "readonly",
                RateLimiter: "readonly",
                TacticalCombatSystem: "readonly",
                Ship: "readonly",
                IDBKeyRange: "readonly",
                GPUBufferUsage: "readonly",
                GPUTextureUsage: "readonly",
                GPUShaderStage: "readonly",
                MouseEvent: "readonly",
                VideoEncoder: "readonly",
                VideoDecoder: "readonly",
                AudioEncoder: "readonly",
                AudioDecoder: "readonly",
                ApplePaySession: "readonly",
                NDEFWriter: "readonly",
                DocumentTimeline: "readonly",
                HTMLElement: "readonly",
                ClipboardItem: "readonly",
                DOMParser: "readonly",
                LiveKitClient: "readonly",
                AnimationGroup: "readonly",
                history: "readonly",
                glCanvas: "writable",
                PhysicsContext: "readonly",
                WebAssembly: "readonly",
                // Web Workers
                postMessage: "readonly",
                self: "readonly",
                Worker: "readonly",
                // Browser/Env
                BroadcastChannel: "readonly",
                XMLHttpRequest: "readonly",
                FontFace: "readonly",
                Node: "readonly",
                KeyboardEvent: "readonly",
                Headers: "readonly",
                // LiveKit
                LiveKitVoiceIntegration: "readonly",
                LivekitClient: "readonly",
                LiveKit: "readonly",
                // Additional Game Managers
                AuthManager: "readonly",
                AlienGenerator: "readonly",
                Achievement: "readonly",
                ReputationSystem: "readonly",
                ShipModule: "readonly",
                ShipDesign: "readonly",
                ShipRenderer: "readonly",
                SatelliteEntity: "readonly",
                ProductionAssetManager: "readonly",
                JumpBridgeManager: "readonly",
                NPCSystem: "readonly",
                FactionManager: "readonly",
                AIGameMaster: "readonly",
                AlienSignalSystem: "readonly",
                LegalSystem: "readonly",
                CombatManager: "readonly",
                ArchaeologyManager: "readonly",
                VictoryManager: "readonly",
                TerraformingManager: "readonly",
                MegastructureSystem: "readonly",
                UniverseManager: "readonly",
                TemporalEngine: "readonly",
                NeuralLinkSystem: "readonly",
                DreamState: "readonly",
                DigitalTwinSystem: "readonly",
                RecursiveSimulation: "readonly",
                AIHistorian: "readonly",
                QuantumComputeEngine: "readonly",
                DNAStorageSystem: "readonly",
                TimeCapsuleManager: "readonly",
                NeuralFabricSystem: "readonly",
                GalacticOversoul: "readonly",
                SentientAgent: "readonly",
                QuantumRenderer: "readonly",
                CRDTManager: "readonly",
                GalacticMeshNetwork: "readonly",
                InterstellarTradeSystem: "readonly",
                IoTManager: "readonly",
                AmbienceEngine: "readonly",
                MutationEngine: "readonly",
                OmegaPoint: "readonly",
                VFXManager: "readonly",
                SpatialAudioManager: "readonly",
                NarrativeManager: "readonly",
                OptimizationManager: "readonly",
                DecalManager: "readonly",
                CharacterCustomizationManager: "readonly",
                Logger: "readonly",
                SoundEngine: "readonly",
                SpaceCombatScene: "readonly",
                TRAIT_DEFINITIONS: "readonly",
                BuildingArchitect: "readonly",
                ExoplanetXRExperience: "readonly",
                GroundWarfareSystem: "readonly",
                FileUploadService: "readonly",
                LiveKitVoiceManager: "readonly",
                CosmicChat: "readonly",
                LiveKitChat: "readonly",
                computerVisionCapabilities: "readonly",
                i: "writable",
                j: "writable",
                k: "writable"
            }
        },
        rules: {
            // Code Quality Rules
            "no-unused-vars": ["warn", { "argsIgnorePattern": "^_", "varsIgnorePattern": "^_" }],
            "no-console": "off", // Console logging is intentional for debugging
            "no-undef": "error",
            "no-redeclare": ["error", { "builtinGlobals": false }],
            "no-unreachable": "error",
            "no-duplicate-case": "error",
            "no-empty": "warn",
            "no-extra-semi": "warn",
            "no-func-assign": "error",
            "no-inner-declarations": "error",
            "no-sparse-arrays": "error",
            "no-unused-labels": "warn",
            "no-useless-escape": "warn",
            "no-var": "warn",
            "prefer-const": "warn",
            "eqeqeq": ["warn", "always"],
            "curly": ["warn", "multi-line"],
            "no-throw-literal": "error",
            "prefer-arrow-callback": "warn",

            // Best Practices
            "no-eval": "error",
            "no-implied-eval": "error",
            "no-new-func": "warn",
            "no-script-url": "error",
            "no-iterator": "warn",
            "no-proto": "warn",
            "no-return-assign": "warn",
            "no-self-compare": "error",
            "no-sequences": "warn",
            "no-throw-literal": "error",
            "no-unmodified-loop-condition": "warn",
            "no-unused-expressions": "warn",
            "no-useless-call": "warn",
            "no-useless-concat": "warn",
            "no-void": "warn",
            "radix": "warn",
            "wrap-iife": ["warn", "any"],

            // Security Rules
            "no-new-wrappers": "warn",
            "no-array-constructor": "warn",
            "no-new-object": "warn",
            "no-param-reassign": ["warn", { "props": false }],

            // Security Plugin Rules (detect-object-injection disabled - too many false positives)
            "security/detect-object-injection": "off",
            "security/detect-non-literal-fs-filename": "warn",
            "security/detect-non-literal-regexp": "warn",
            "security/detect-non-literal-require": "warn",
            "security/detect-unsafe-regex": "warn",
            "security/detect-buffer-noassert": "warn",
            "security/detect-child-process": "warn",
            "security/detect-disable-mustache-escape": "warn",
            "security/detect-eval-with-expression": "error",
            "security/detect-no-csrf-before-method-override": "warn",
            "security/detect-possible-timing-attacks": "warn",
            "security/detect-pseudoRandomBytes": "warn",

            // SonarJS Plugin Rules (only valid rules)
            "sonarjs/cognitive-complexity": ["warn", 15],
            "sonarjs/no-duplicate-string": "warn",
            "sonarjs/no-identical-expressions": "error",
            "sonarjs/no-use-of-empty-return-value": "warn",
            "sonarjs/prefer-immediate-return": "warn",
            "sonarjs/prefer-object-literal": "warn",
            "sonarjs/prefer-single-boolean-return": "warn",

            // Complexity
            "complexity": ["warn", 20],
            "max-depth": ["warn", 5],
            "max-lines-per-function": ["warn", { "max": 200, "skipBlankLines": true, "skipComments": true }],
            "max-params": ["warn", 5],
            "max-statements": ["warn", 30]
        }
    },
    // Node.js/Backend configuration
    {
        files: ["backend/**/*.js", "stellar-ai-cli/**/*.js", "count-exoplanets.js", "download-new-music.js", "extract-wix-graph.js", "package-cli.js", "setup-music.js"],
        plugins: {
            security,
            sonarjs
        },
        languageOptions: {
            ecmaVersion: "latest",
            sourceType: "script",
            globals: {
                require: "readonly",
                module: "readonly",
                exports: "readonly",
                __dirname: "readonly",
                __filename: "readonly",
                process: "readonly",
                console: "readonly",
                Buffer: "readonly",
                global: "readonly"
            }
        },
        rules: {
            "no-unused-vars": ["warn", { "argsIgnorePattern": "^_", "varsIgnorePattern": "^_" }],
            "no-console": "off",
            "no-undef": "error",
            "radix": "warn",
            "complexity": ["warn", 25],
            "max-statements": ["warn", 40],
            "no-redeclare": ["error", { "builtinGlobals": false }],

            // Security Plugin Rules (Backend)
            "security/detect-object-injection": "off",
            "security/detect-non-literal-fs-filename": "warn",
            "security/detect-non-literal-regexp": "warn",
            "security/detect-non-literal-require": "warn",
            "security/detect-unsafe-regex": "warn",
            "security/detect-child-process": "error",
            "security/detect-eval-with-expression": "error",

            // SonarJS Plugin Rules (Backend)
            "sonarjs/cognitive-complexity": ["warn", 20],
            "sonarjs/no-duplicate-string": "warn",
            "sonarjs/no-identical-expressions": "error"
        }
    },
    // ARC Dataset specific globals
    {
        files: ["arc-dataset/**/*.js"],
        languageOptions: {
            globals: {
                // Browser globals
                window: "readonly",
                document: "readonly",
                console: "readonly",
                $: "readonly",
                jQuery: "readonly",
                // ARC specific
                Grid: "readonly",
                MAX_CELL_SIZE: "readonly",
                target: "writable",
                height: "writable",
                width: "writable",
                candidate_height: "writable",
                candidate_width: "writable",
                row_count: "writable",
                col_count: "writable",
                classesToRemove: "writable",
                selected: "writable",
                cell: "writable",
                symbol: "writable",
                mode: "writable",
                floodfillFromLocation: "readonly",
                setCellSymbol: "readonly",
                parseSizeTuple: "readonly",
                COPY_PASTE_DATA: "readonly",
                x: "writable",
                y: "writable",
                minx: "writable",
                miny: "writable",
                xs: "writable",
                ys: "writable",
                symbols: "writable",
                newx: "writable",
                newy: "writable",
                res: "writable",
                targetx: "writable",
                targety: "writable",
                CURRENT_INPUT_GRID: "readonly",
                CURRENT_OUTPUT_GRID: "readonly",
                TEST_PAIRS: "readonly",
                CURRENT_TEST_PAIR_INDEX: "readonly",
                convertSerializedGridToGridObject: "readonly",
                fillJqGridWithData: "readonly",
                fitCellsToContainer: "readonly",
                errorMsg: "readonly",
                infoMsg: "readonly",
                test: "writable",
                train: "writable",
                reference_output: "writable",
                submitted_output: "writable",
                ref_row: "writable",
                pair: "writable",
                values: "writable",
                input_grid: "writable",
                output_grid: "writable",
                jqInputGrid: "writable",
                jqOutputGrid: "writable",
                big_space: "writable",
                copyJqGridToDataGrid: "readonly",
                grid: "writable",
                size: "writable",
                symbol_preview: "writable",
                toolMode: "writable",
                spacerBottom: "writable",
                s: "writable",
                i: "writable",
                j: "writable",
                k: "writable"
            }
        },
        rules: {
            "no-redeclare": "off"
        }
    },
    // Test configuration
    {
        files: ["tests/**/*.js", "**/*.spec.js", "**/*.test.js"],
        languageOptions: {
            globals: {
                describe: "readonly",
                it: "readonly",
                test: "readonly",
                expect: "readonly",
                beforeEach: "readonly",
                afterEach: "readonly",
                beforeAll: "readonly",
                afterAll: "readonly",
                jest: "readonly",
                vi: "readonly" // Vitest support
            }
        }
    }
];
