name = "exoplanet-assets"
main = "assets-worker.js"
compatibility_date = "2023-10-30"

[[r2_buckets]]
binding = "EXOPLANET_ASSETS"
bucket_name = "exoplanet-pioneer-assets"

[vars]
ENVIRONMENT = "production"
