#!/usr/bin/env python3
"""Create a filtered, deterministic GitHub CI snapshot from a committed Git ref.

The canonical GitLab repository contains multi-gigabyte packaged games, backups and
binary runtime archives that are irrelevant to the website/Pioneer test suite and
cannot be mirrored to GitHub normally. This script materializes only CI-relevant
tracked files directly from Git objects, never from the working tree.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path, PurePosixPath

DEFAULT_MAX_BLOB_BYTES = 5 * 1024 * 1024
EXCLUDED_PREFIXES = (
    "public/",                 # generated by build-pages.ps1
    "node_modules/",           # restored by npm ci in GitHub Actions
    "total-war-2/",            # packaged desktop game payload
    "mods_full_backup/",       # backup payload
    "files/",                  # packaged runtime payload
    "overrides/",              # Java runtime override payload
    "cheerpj_dist/",           # vendored browser JVM runtime
    "cheerpj-3.0/",            # vendored browser JVM runtime
    "swf/",                    # legacy binary archive
    "usr/",                    # copied runtime tree
    "data_backup/",            # redundant data backup
    "test-results-smoke/",     # generated test evidence
    "tbench/",                 # benchmark workspace
    "tbench_workspace/",       # benchmark workspace
    "experimental/sentient-browser/models/",  # local model weights
    "assets/models_backup/",   # duplicate model archive
)

# These large diagnostic/runtime files live at repository root and are not inputs to
# the website build or its tests. The generic blob limit also excludes them, but the
# names make the policy intentional and reviewable.
EXCLUDED_PATHS = {
    ".env",
    "GEMINI-API-KEY-SETUP.md",
    "GET-SUPABASE-CREDENTIALS.md",
    "GITLAB-API-KEYS-SETUP.md",
    "REQUIRED-API-KEYS-GITLAB.md",
    "SETUP-API-KEYS.md",
    "UPDATE-GEMINI-API-KEY.md",
    "backend/LIVE-API-WITH-API-KEY-SUPPORT.md",
    "inject-api-keys.ps1",
    "localhost3.har",
    "localhost4.har",
    "lint_errors.json",
    "tmp_shard.bin",
    "merged_game.jar",
    "overrides.jar",
    "graphics.zip",
    "jre8u271-linux-x64.tar.gz",
    "Printout.mht",
}


def run_git(repo: Path, *args: str, text: bool = False) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args],
        cwd=repo,
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=text,
    )


def parse_tree(repo: Path, ref: str) -> list[dict]:
    raw = run_git(repo, "ls-tree", "-rlz", ref).stdout
    entries: list[dict] = []
    for record in raw.split(b"\0"):
        if not record:
            continue
        meta, path_bytes = record.split(b"\t", 1)
        parts = meta.split()
        if len(parts) < 4 or parts[1] != b"blob":
            continue
        path = path_bytes.decode("utf-8", errors="surrogateescape")
        entries.append({
            "mode": parts[0].decode("ascii"),
            "sha": parts[2].decode("ascii"),
            "size": int(parts[3]),
            "path": path,
        })
    return entries


def exclusion_reason(entry: dict, max_blob_bytes: int) -> str | None:
    path = entry["path"]
    name = PurePosixPath(path).name.lower()
    if name == ".env" or name.startswith(".env."):
        return "credential-material"
    if path in EXCLUDED_PATHS:
        return "explicit-runtime-or-diagnostic"
    if path.startswith(EXCLUDED_PREFIXES):
        return "excluded-prefix"
    if entry["size"] > max_blob_bytes:
        return f"blob-over-{max_blob_bytes}"
    return None


def safe_destination(root: Path, posix_path: str) -> Path:
    pure = PurePosixPath(posix_path)
    if pure.is_absolute() or ".." in pure.parts:
        raise ValueError(f"Unsafe tracked path: {posix_path}")
    dest = root.joinpath(*pure.parts)
    resolved_root = root.resolve()
    resolved_parent = dest.parent.resolve()
    if resolved_root != resolved_parent and resolved_root not in resolved_parent.parents:
        raise ValueError(f"Tracked path escapes snapshot root: {posix_path}")
    return dest


def read_blob(batch: subprocess.Popen, sha: str) -> bytes:
    assert batch.stdin and batch.stdout
    batch.stdin.write((sha + "\n").encode("ascii"))
    batch.stdin.flush()
    header = batch.stdout.readline()
    if not header:
        raise RuntimeError(f"git cat-file ended while reading {sha}")
    parts = header.rstrip(b"\n").split()
    if len(parts) == 2 and parts[1] == b"missing":
        raise RuntimeError(f"Missing Git object {sha}")
    if len(parts) != 3 or parts[1] != b"blob":
        raise RuntimeError(f"Unexpected cat-file response for {sha}: {header!r}")
    size = int(parts[2])
    data = batch.stdout.read(size)
    terminator = batch.stdout.read(1)
    if len(data) != size or terminator != b"\n":
        raise RuntimeError(f"Truncated Git blob {sha}")
    return data


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", default=".", help="Canonical Git repository")
    parser.add_argument("--ref", default="HEAD", help="Committed source ref")
    parser.add_argument("--output", required=True, help="Destination snapshot directory")
    parser.add_argument("--max-blob-mib", type=float, default=5.0)
    parser.add_argument("--keep-output", action="store_true", help="Do not delete a pre-existing destination")
    args = parser.parse_args()

    repo = Path(args.repo).resolve()
    output = Path(args.output).resolve()
    max_blob_bytes = max(1, int(args.max_blob_mib * 1024 * 1024))
    source_sha = run_git(repo, "rev-parse", args.ref, text=True).stdout.strip()

    if output.exists() and not args.keep_output:
        shutil.rmtree(output)
    output.mkdir(parents=True, exist_ok=True)

    entries = parse_tree(repo, args.ref)
    included: list[dict] = []
    excluded: list[dict] = []
    for entry in entries:
        reason = exclusion_reason(entry, max_blob_bytes)
        if reason:
            excluded.append({"path": entry["path"], "size": entry["size"], "reason": reason})
        else:
            included.append(entry)

    # Required CI inputs fail closed if the filter policy accidentally removes them.
    required = {
        ".github/workflows/ci-cd.yml",
        "build-pages.ps1",
        "package.json",
        "package-lock.json",
        "exoplanet-pioneer.html",
        "exoplanet-pioneer.js",
        "planet-generator.js",
        "pioneer-raytracing.js",
        "local-system-view.js",
        "scripts/pioneer-playwright-workload.mjs",
        "scripts/pioneer-advanced-rendering-smoke.mjs",
    }
    included_paths = {entry["path"] for entry in included}
    missing = sorted(required - included_paths)
    if missing:
        raise SystemExit(f"CI snapshot policy excluded required files: {missing}")

    batch = subprocess.Popen(
        ["git", "cat-file", "--batch"],
        cwd=repo,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    written_bytes = 0
    try:
        for index, entry in enumerate(included, 1):
            dest = safe_destination(output, entry["path"])
            dest.parent.mkdir(parents=True, exist_ok=True)
            data = read_blob(batch, entry["sha"])
            dest.write_bytes(data)
            written_bytes += len(data)
            if os.name != "nt" and entry["mode"] == "100755":
                dest.chmod(dest.stat().st_mode | 0o111)
            if index % 1000 == 0:
                print(f"materialized {index}/{len(included)} files", file=sys.stderr)
    finally:
        if batch.stdin:
            batch.stdin.close()
        batch.terminate()
        batch.wait(timeout=10)

    manifest = {
        "schema": 1,
        "source": "gitlab.com/adybag14-group/starisdons",
        "sourceRef": args.ref,
        "sourceSha": source_sha,
        "maxBlobBytes": max_blob_bytes,
        "includedFiles": len(included),
        "includedBytes": written_bytes,
        "excludedFiles": len(excluded),
        "excludedBytes": sum(item["size"] for item in excluded),
        "excludedPrefixes": list(EXCLUDED_PREFIXES),
        "excludedPaths": sorted(EXCLUDED_PATHS),
        "largestExcluded": sorted(excluded, key=lambda item: item["size"], reverse=True)[:50],
    }
    (output / ".gitlab-source-sha").write_text(source_sha + "\n", encoding="ascii")
    (output / ".github-ci-snapshot.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    print(json.dumps({
        "sourceSha": source_sha,
        "includedFiles": len(included),
        "includedMiB": round(written_bytes / (1024 * 1024), 2),
        "excludedFiles": len(excluded),
        "excludedGiB": round(sum(item["size"] for item in excluded) / (1024 ** 3), 3),
        "output": str(output),
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
