#!/usr/bin/env python3
"""Create a filtered, deterministic GitHub CI snapshot from a committed Git ref.

The canonical GitLab repository contains multi-gigabyte packaged games, backups and
binary runtime archives that are irrelevant to the website/Pioneer test suite and
cannot be mirrored to GitHub normally. This script materializes only CI-relevant
tracked files directly from Git objects, never from the working tree.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path, PurePosixPath

DEFAULT_MAX_BLOB_BYTES = 5 * 1024 * 1024
OVERSIZE_PRODUCTION_PREFIXES = (
    "audio/",  # build-pages.ps1 publishes the complete production soundtrack
)
OVERSIZE_PRODUCTION_PATHS = {
    "assets/models/ships/viper.glb",
    "assets/models/defense/missile_battery.glb",
}
EXCLUDED_PREFIXES = (
    "public/",                 # generated by build-pages.ps1
    "node_modules/",           # restored by npm ci in GitHub Actions
    "total-war-2/",            # packaged desktop game payload
    "mods_full_backup/",       # backup payload
    "files/",                  # packaged runtime payload
    "overrides/",              # Java runtime override payload
    "cheerpj_dist/",           # vendored browser JVM runtime
    "cheerpj-3.0/",            # vendored browser JVM runtime
    "swf/",                    # legacy binary archive
    "usr/",                    # copied runtime tree
    "data_backup/",            # redundant data backup
    "test-results-smoke/",     # generated test evidence
    "tbench/",                 # benchmark workspace
    "tbench_workspace/",       # benchmark workspace
    "experimental/sentient-browser/models/",  # local model weights
    "assets/models_backup/",   # duplicate model archive
)

# These large diagnostic/runtime files live at repository root and are not inputs to
# the website build or its tests. The generic blob limit also excludes them, but the
# names make the policy intentional and reviewable.
EXCLUDED_PATHS = {
    ".env",
    "GEMINI-API-KEY-SETUP.md",
    "GET-SUPABASE-CREDENTIALS.md",
    "GITLAB-API-KEYS-SETUP.md",
    "REQUIRED-API-KEYS-GITLAB.md",
    "SETUP-API-KEYS.md",
    "UPDATE-GEMINI-API-KEY.md",
    "backend/LIVE-API-WITH-API-KEY-SUPPORT.md",
    "inject-api-keys.ps1",
    "localhost3.har",
    "localhost4.har",
    "lint_errors.json",
    "tmp_shard.bin",
    "merged_game.jar",
    "overrides.jar",
    "graphics.zip",
    "jre8u271-linux-x64.tar.gz",
    "Printout.mht",
}


def run_git(repo: Path, *args: str, text: bool = False) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args],
        cwd=repo,
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=text,
    )


def git_ignored_paths(repo: Path, entries: list[dict]) -> set[str]:
    """Return tracked paths excluded by the checked-out ref's ignore policy."""
    payload = b"\0".join(
        entry["path"].encode("utf-8", errors="surrogateescape") for entry in entries
    ) + b"\0"
    result = subprocess.run(
        ["git", "check-ignore", "--no-index", "-z", "--stdin"],
        cwd=repo,
        input=payload,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode not in (0, 1):
        raise RuntimeError(
            "git check-ignore failed: "
            + result.stderr.decode("utf-8", errors="replace").strip()
        )
    return {
        item.decode("utf-8", errors="surrogateescape")
        for item in result.stdout.split(b"\0")
        if item
    }


def parse_tree(repo: Path, ref: str) -> list[dict]:
    raw = run_git(repo, "ls-tree", "-rlz", ref).stdout
    entries: list[dict] = []
    for record in raw.split(b"\0"):
        if not record:
            continue
        meta, path_bytes = record.split(b"\t", 1)
        parts = meta.split()
        if len(parts) < 4 or parts[1] != b"blob":
            continue
        path = path_bytes.decode("utf-8", errors="surrogateescape")
        entries.append({
            "mode": parts[0].decode("ascii"),
            "sha": parts[2].decode("ascii"),
            "size": int(parts[3]),
            "path": path,
        })
    return entries


def exclusion_reason(entry: dict, max_blob_bytes: int) -> str | None:
    path = entry["path"]
    name = PurePosixPath(path).name.lower()
    if name == ".env" or name.startswith(".env."):
        return "credential-material"
    if path in EXCLUDED_PATHS:
        return "explicit-runtime-or-diagnostic"
    if path.startswith(EXCLUDED_PREFIXES):
        return "excluded-prefix"
    is_required_production_asset = (
        path in OVERSIZE_PRODUCTION_PATHS
        or path.startswith(OVERSIZE_PRODUCTION_PREFIXES)
    )
    if entry["size"] > max_blob_bytes and not is_required_production_asset:
        return f"blob-over-{max_blob_bytes}"
    return None


def safe_destination(root: Path, posix_path: str) -> Path:
    pure = PurePosixPath(posix_path)
    if pure.is_absolute() or ".." in pure.parts:
        raise ValueError(f"Unsafe tracked path: {posix_path}")
    dest = root.joinpath(*pure.parts)
    resolved_root = root.resolve()
    resolved_parent = dest.parent.resolve()
    if resolved_root != resolved_parent and resolved_root not in resolved_parent.parents:
        raise ValueError(f"Tracked path escapes snapshot root: {posix_path}")
    return dest


def read_blob(batch: subprocess.Popen, sha: str) -> bytes:
    assert batch.stdin and batch.stdout
    batch.stdin.write((sha + "\n").encode("ascii"))
    batch.stdin.flush()
    header = batch.stdout.readline()
    if not header:
        raise RuntimeError(f"git cat-file ended while reading {sha}")
    parts = header.rstrip(b"\n").split()
    if len(parts) == 2 and parts[1] == b"missing":
        raise RuntimeError(f"Missing Git object {sha}")
    if len(parts) != 3 or parts[1] != b"blob":
        raise RuntimeError(f"Unexpected cat-file response for {sha}: {header!r}")
    size = int(parts[2])
    data = batch.stdout.read(size)
    terminator = batch.stdout.read(1)
    if len(data) != size or terminator != b"\n":
        raise RuntimeError(f"Truncated Git blob {sha}")
    return data


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", default=".", help="Canonical Git repository")
    parser.add_argument("--ref", default="HEAD", help="Committed source ref")
    parser.add_argument("--output", required=True, help="Destination snapshot directory")
    parser.add_argument("--max-blob-mib", type=float, default=5.0)
    parser.add_argument("--keep-output", action="store_true", help="Do not delete a pre-existing destination")
    args = parser.parse_args()

    repo = Path(args.repo).resolve()
    output = Path(args.output).resolve()
    max_blob_bytes = max(1, int(args.max_blob_mib * 1024 * 1024))
    source_sha = run_git(repo, "rev-parse", args.ref, text=True).stdout.strip()
    checked_out_sha = run_git(repo, "rev-parse", "HEAD", text=True).stdout.strip()

    if source_sha != checked_out_sha:
        raise SystemExit(
            "Snapshot ref must match the checked-out HEAD so the committed .gitignore "
            "policy can be applied deterministically."
        )
    ignore_diff = subprocess.run(
        ["git", "diff", "--quiet", "HEAD", "--", ".gitignore"],
        cwd=repo,
        check=False,
    )
    if ignore_diff.returncode != 0:
        raise SystemExit("Refusing to snapshot with uncommitted .gitignore changes.")

    if output.exists() and not args.keep_output:
        shutil.rmtree(output)
    output.mkdir(parents=True, exist_ok=True)

    entries = parse_tree(repo, args.ref)
    ignored_paths = git_ignored_paths(repo, entries)
    included: list[dict] = []
    excluded: list[dict] = []
    for entry in entries:
        reason = exclusion_reason(entry, max_blob_bytes)
        if reason is None and entry["path"] in ignored_paths:
            reason = "gitignore-policy"
        if reason:
            excluded.append({"path": entry["path"], "size": entry["size"], "reason": reason})
        else:
            included.append(entry)

    # Required CI inputs fail closed if the filter policy accidentally removes them.
    required = {
        ".github/workflows/ci-cd.yml",
        "build-pages.ps1",
        "package.json",
        "package-lock.json",
        "exoplanet-pioneer.html",
        "exoplanet-pioneer.js",
        "planet-generator.js",
        "pioneer-raytracing.js",
        "local-system-view.js",
        "pioneer-runtime.js",
        "pioneer-cinematic-renderer.js",
        "pioneer-universe-streaming.js",
        "games-archive-index.json",
        "scripts/check-current-tree-secrets.mjs",
        "scripts/pioneer-playwright-workload.mjs",
        "scripts/pioneer-workload-fixtures.mjs",
        "scripts/pioneer-advanced-rendering-smoke.mjs",
        "tests/e2e/smoke-ci.spec.js",
        "tests/e2e/site-overhaul.spec.js",
        "tests/e2e/local-platform-remediation.spec.js",
        "tests/e2e/privacy-tracker.spec.js",
        "tests/e2e/pioneer-star-maps-advanced.spec.js",
        "tests/e2e/accessibility-all-pages.spec.js",
        "tests/e2e/pioneer-runtime-v2.spec.js",
        "tests/e2e/pioneer-universe-streaming.spec.js",
        "tests/e2e/pioneer-cinematic-combat.spec.js",
        "tests/e2e/site-action-contracts.spec.js",
        "tests/e2e/site-shared-actions.spec.js",
        "tests/e2e/bonsai-loader.spec.js",
        "tests/e2e/games-archive-contracts.spec.js",
        "tests/e2e/pioneer-science-deck.spec.js",
        "tests/e2e/database-lazy-loader.spec.js",
        "tests/e2e/helpers/pioneer-functional-profile.js",
        "assets/models/ships/viper.glb",
        "assets/models/defense/missile_battery.glb",
    }
    included_paths = {entry["path"] for entry in included}
    missing = sorted(required - included_paths)
    if missing:
        raise SystemExit(f"CI snapshot policy excluded required files: {missing}")

    batch = subprocess.Popen(
        ["git", "cat-file", "--batch"],
        cwd=repo,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    written_bytes = 0
    try:
        for index, entry in enumerate(included, 1):
            dest = safe_destination(output, entry["path"])
            dest.parent.mkdir(parents=True, exist_ok=True)
            data = read_blob(batch, entry["sha"])
            dest.write_bytes(data)
            written_bytes += len(data)
            if os.name != "nt" and entry["mode"] == "100755":
                dest.chmod(dest.stat().st_mode | 0o111)
            if index % 1000 == 0:
                print(f"materialized {index}/{len(included)} files", file=sys.stderr)
    finally:
        if batch.stdin:
            batch.stdin.close()
        batch.terminate()
        batch.wait(timeout=10)

    manifest = {
        "schema": 1,
        "source": "gitlab.com/adybag14-group/starisdons",
        "sourceRef": args.ref,
        "sourceSha": source_sha,
        "maxBlobBytes": max_blob_bytes,
        "includedFiles": len(included),
        "includedBytes": written_bytes,
        "excludedFiles": len(excluded),
        "excludedBytes": sum(item["size"] for item in excluded),
        "excludedPrefixes": list(EXCLUDED_PREFIXES),
        "excludedPaths": sorted(EXCLUDED_PATHS),
        "largestExcluded": sorted(excluded, key=lambda item: item["size"], reverse=True)[:50],
    }
    # These files are committed to the filtered GitHub mirror. Write bytes so
    # Windows does not translate LF to CRLF and make `git diff --check` reject
    # the generated authority metadata as trailing whitespace.
    (output / ".gitlab-source-sha").write_bytes((source_sha + "\n").encode("ascii"))
    (output / ".github-ci-snapshot.json").write_bytes((json.dumps(manifest, indent=2) + "\n").encode("utf-8"))

    print(json.dumps({
        "sourceSha": source_sha,
        "includedFiles": len(included),
        "includedMiB": round(written_bytes / (1024 * 1024), 2),
        "excludedFiles": len(excluded),
        "excludedGiB": round(sum(item["size"] for item in excluded) / (1024 ** 3), 3),
        "output": str(output),
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
