export const SITE_ORIGIN = 'https://adrianotothestar.com';

export const SITE_PAGES = [
  ['index.html', 'Interstellar Travel Agency | Explore Worlds Beyond Earth', 'Explore exoplanets, future routes, interactive star maps, space technology, and research from the Adriano To The Star interstellar travel concept.'],
  ['about.html', 'About the Project | Adriano To The Star', 'A short introduction to the Adriano To The Star space education and browser-experiment project.'],
  ['ai-fairness.html', 'AI Fairness for Space Research | Adriano To The Star', 'Review practical fairness principles, bias checks, and responsible-AI safeguards for models used across the Adriano To The Star research platform.'],
  ['ai-metrics-dashboard.html', 'AI Model Performance Metrics | Adriano To The Star', 'Explore model quality, latency, reliability, and evaluation metrics for artificial-intelligence experiments on Adriano To The Star.'],
  ['ai-predictions.html', 'AI Predictions for Exoplanet Research | Adriano To The Star', 'Explore clearly labeled AI-assisted forecasts for exoplanet discovery, habitability research, and future space missions.'],
  ['analytics-dashboard.html', 'Space Platform Analytics | Adriano To The Star', 'Explore high-level activity, discovery, engagement, and platform metrics across Adriano To The Star.'],
  ['api.html', 'Developer API | Adriano To The Star', 'Review the Adriano To The Star developer API concept, its exoplanet data capabilities, integration guidance, and current availability.'],
  ['badges.html', 'Badges and Achievements | Adriano To The Star', 'Explore the discovery, learning, and community achievements available to Adriano To The Star members.'],
  ['blog.html', 'Space Exploration Blog | Adriano To The Star', 'Read Adriano To The Star articles about exoplanets, astronomy, interactive technology, and the future of space exploration.'],
  ['book-online.html', 'Book an Adriano To The Star Experience', 'Review booking options and begin an Adriano To The Star exoplanet discovery or celestial experience.'],
  ['broadband-checker.html', 'Broadband Deal Checker | Adriano To The Star', 'Compare broadband deal information with the Adriano To The Star experimental broadband checker and review its availability guidance.'],
  ['brotli2-memory-profiler.html', 'Brotli2 Memory Profiler | Adriano To The Star', 'Inspect Brotli2 compression memory scenarios with an interactive profiling utility from the Adriano To The Star engineering lab.'],
  ['business-promise.html', 'Business Promise | Adriano To The Star', 'Read the Adriano To The Star commitment to transparent claims, responsible experimentation, practical innovation, and clear customer expectations.'],
  ['dashboard.html', 'Member Dashboard | Adriano To The Star', 'Manage your Adriano To The Star profile, saved discoveries, claimed exoplanets, and member activity from one dashboard.'],
  ['database-analytics.html', 'Exoplanet Database Analytics | Adriano To The Star', 'Explore visual summaries and analytical views of the Adriano To The Star exoplanet database.'],
  ['database.html', 'Exoplanet Database | Adriano To The Star', 'Search and analyze more than 9,500 Kepler objects with discovery details, statistics, and habitability context.'],
  ['education.html', 'Galactic Education | Adriano To The Star', 'Learn planetary science with interactive 3D planet textures, astronomy lessons, and guided space-learning modules.'],
  ['event-calendar.html', 'Space Events Calendar | Adriano To The Star', 'Browse upcoming astronomy, community, learning, and space-exploration events in the Adriano To The Star calendar.'],
  ['events.html', 'Events | Adriano To The Star', 'Discover astronomy, community, learning, and space-exploration events from Adriano To The Star.'],
  ['exoplanet-pioneer.html', 'Exoplanet Pioneer Colony Simulation | Adriano To The Star', 'Build a research colony on Kepler-186f, manage resources, explore modeled scenarios, and learn through an advanced browser simulation.'],
  ['file-storage.html', 'File Storage | Adriano To The Star', 'Review file-storage tools and availability for Adriano To The Star member content and project data.'],
  ['followers.html', 'Followers | Adriano To The Star', 'View follower relationships and community connections on Adriano To The Star.'],
  ['forum.html', 'Community Forum | Adriano To The Star', 'Join Adriano To The Star discussions about exoplanets, astronomy, technology, games, and future missions.'],
  ['games.html', 'Browser Games Archive | Adriano To The Star', 'Explore the Adriano To The Star browser-games archive, including preserved classics and space-themed experiences.'],
  ['groups.html', 'Community Groups | Adriano To The Star', 'Find and join Adriano To The Star groups focused on astronomy, exoplanet research, games, and technology.'],
  ['gta-6-videos.html', 'GTA 6 Video Archive | Adriano To The Star', 'Browse the Adriano To The Star GTA 6 video archive and its contextual information.'],
  ['hiv-market-analysis.html', 'HIV Market Analysis | Adriano To The Star', 'Review a strategic assessment of HIV epidemiology, institutional procurement, customer focus, and market planning in southern Africa.'],
  ['loyalty.html', 'Loyalty Program | Adriano To The Star', 'Explore Adriano To The Star loyalty benefits, progress, and member rewards.'],
  ['marketplace.html', 'Planet Marketplace | Adriano To The Star', 'Explore clearly described experimental exoplanet claims, rentals, collectibles, and space-project crowdfunding concepts.'],
  ['mechgen.html', 'MechGen AI Reaction Design Studio | Adriano To The Star', 'Explore organic reaction mechanisms with AI-assisted chemical analysis and molecular rendering in the experimental MechGen studio.'],
  ['members.html', 'Member Directory | Adriano To The Star', 'Explore the Adriano To The Star member community and access member account tools.'],
  ['messaging.html', 'Direct Messages | Adriano To The Star', 'Access direct community messaging and conversation tools on Adriano To The Star.'],
  ['monitor.html', 'Website System Monitor | Adriano To The Star', 'Review current public website health and performance signals for Adriano To The Star.'],
  ['newsletter.html', 'Space Newsletter | Adriano To The Star', 'Subscribe for Adriano To The Star updates about exoplanets, astronomy, interactive projects, and future missions.'],
  ['offline.html', 'Offline | Adriano To The Star', 'A resilient offline fallback for previously visited Adriano To The Star content.', { indexable: false }],
  ['projects.html', 'Advanced Browser Projects | Adriano To The Star', 'Launch tested WebGPU, procedural-graphics, local-AI, WebXR, peer-to-peer, and device-integration experiments from the Adriano To The Star flight lab.'],
  ['privacy.html', 'Privacy Centre | Adriano To The Star', 'Learn what Adriano To The Star processes, which browser-local features store data on your device, how external services are disclosed, and how to exercise your privacy rights.'],
  ['secure-chat.html', 'Secure Chat | Adriano To The Star', 'Review the Adriano To The Star secure-chat experiment, privacy guidance, and current availability.'],
  ['service-page/galaxy-object-trading.html', 'Galaxy Object Trading | Adriano To The Star', 'Explore the clearly labeled Galaxy Object Trading concept for celestial assets, claims, and marketplace activity.', { parent: ['Marketplace', 'marketplace.html'] }],
  ['shop.html', 'Shop | Adriano To The Star', 'Browse space-themed digital products, collectibles, services, and Adriano To The Star merchandise.'],
  ['space-dashboard.html', 'Live Space Data Dashboard | Adriano To The Star', 'Explore a browser dashboard for public launch, mission, and exoplanet data with clear source and fallback status.'],
  ['star-maps.html', 'Interactive Star Maps | Adriano To The Star', 'Explore stars, exoplanet systems, and astronomical context with interactive maps from Adriano To The Star.'],
  ['starsector-login.html', 'Starsector Access Portal | Adriano To The Star', 'Access the Adriano To The Star launch portal for the separately hosted Starsector browser experience.'],
  ['starsector.html', 'Opening Starsector | Adriano To The Star', 'Redirect to the separately hosted Starsector browser experience.', { indexable: false }],
  ['stellar-ai.html', 'Stellar AI Cosmic Assistant | Adriano To The Star', 'Explore the Stellar AI experiment for space-data questions, celestial context, and clearly labeled AI-assisted responses.'],
  ['total-war-2.html', 'Medieval II: Total War Archive | Adriano To The Star', 'Explore the Adriano To The Star Medieval II: Total War archive and browser-play information.'],
  ['tracker.html', 'Stellar Neighbourhood Tracker | Adriano To The Star', 'Explore a responsive 3D map of nearby stars, confirmed exoplanet hosts, and recent NASA mission discoveries using an authoritative build-time research snapshot.']
].map(([path, title, description, options = {}]) => ({ path, title, description, indexable: true, ...options }));

export function canonicalUrl(page) {
  return page.path === 'index.html' ? `${SITE_ORIGIN}/` : `${SITE_ORIGIN}/${page.path}`;
}
